log_file: "/var/log/syslog"
log_pattern: "Out of memory: Kill process (\\d+) \\((\\w+)\\)"
exporter_port: "9090"
repeat_interval: 10   # Пауза перед следующей проверкой в секундах
state_file: "/opt/syslog_exporter/state.yaml"
